# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 04:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogsPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mate_start_date', models.DateField(blank=True, null=True, verbose_name='date of mate start')),
                ('mate_end_date', models.DateField(blank=True, null=True, verbose_name='date of mate end')),
                ('born_date', models.DateField(null=True, verbose_name='date of born')),
                ('wean_start_date', models.DateField(blank=True, null=True, verbose_name='date of wean start')),
                ('wean_end_date', models.DateField(blank=True, null=True, verbose_name='date of wean end')),
                ('litter', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strain', models.CharField(default='C57BL/6', max_length=50)),
                ('line', models.CharField(default='WT', max_length=50)),
                ('locus', models.CharField(max_length=50, null=True)),
                ('date', models.DateField(verbose_name='Chow Added Date')),
                ('time', models.TimeField(verbose_name='Chow Added Time')),
                ('amount', models.FloatField(verbose_name='Chow Added Amount')),
            ],
        ),
        migrations.CreateModel(
            name='Genotype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strain', models.CharField(default='C57BL/6', max_length=50)),
                ('line', models.CharField(default='WT', max_length=50)),
                ('locus', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InjectVirus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200, null=True)),
                ('date', models.DateField(verbose_name='Bedding Added Date')),
                ('time', models.TimeField(verbose_name='Bedding Added Time')),
                ('note', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mouse_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(default='?', max_length=50)),
                ('source', models.IntegerField(choices=[(0, '饲养产生后代'), (1, '广东省实验动物中心'), (2, '南京模式生物中心'), (9, 'unknown')], default=0)),
                ('status', models.IntegerField(choices=[(0, 'idle'), (1, 'suckling'), (2, 'mating'), (3, 'lactating'), (4, 'dead'), (9, 'unknown')], default=0)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('dod', models.DateField(blank=True, null=True, verbose_name='date of death')),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('corpse', models.IntegerField(choices=[(0, '丢弃'), (1, '实验'), (2, '送出')], default=0)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Breed')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Feed')),
                ('genotype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Genotype')),
            ],
        ),
        migrations.CreateModel(
            name='Phenotype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Weighting Date')),
                ('time', models.TimeField(verbose_name='Weighting Time')),
                ('weight', models.FloatField(verbose_name='Weight')),
                ('health', models.CharField(max_length=50, null=True)),
                ('color', models.IntegerField(choices=[(0, 'Black'), (1, 'White'), (2, 'Nake')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='mouse',
            name='phenotype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Phenotype'),
        ),
    ]
