# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogsPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('mate_start_date', models.DateField(verbose_name='date of mate start')),
                ('mate_end_date', models.DateField(blank=True, null=True, verbose_name='date of mate end')),
                ('pregnant', models.NullBooleanField(default=None)),
                ('infanticide', models.NullBooleanField(default=None)),
                ('born_date', models.DateField(null=True, verbose_name='date of born')),
                ('wean_start_date', models.DateField(blank=True, null=True, verbose_name='date of wean start')),
                ('wean_end_date', models.DateField(blank=True, null=True, verbose_name='date of wean end')),
                ('litter_count', models.IntegerField(null=True)),
                ('genotyped', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Chow Added Date')),
                ('chow', models.CharField(default='Normal', max_length=200)),
                ('drink', models.CharField(default='Normal', max_length=200)),
                ('amount', models.FloatField(verbose_name='Chow Added Amount')),
            ],
        ),
        migrations.CreateModel(
            name='Genotype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strain', models.CharField(default='C57BL/6', max_length=50)),
                ('line', models.CharField(default='WT', max_length=50)),
                ('locus', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Weighting Date')),
                ('health', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InjectVirus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200, null=True)),
                ('date', models.DateField(verbose_name='Bedding Added Date')),
                ('time', models.TimeField(verbose_name='Bedding Added Time')),
                ('note', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mouse_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(default='?', max_length=50)),
                ('source', models.CharField(choices=[('饲养产生后代', '饲养产生后代'), ('广东省实验动物中心', '广东省实验动物中心'), ('南京模式生物中心', '南京模式生物中心'), ('unknown', 'unknown')], default='饲养产生后代', max_length=50)),
                ('status', models.CharField(choices=[('idle', 'idle'), ('suckling', 'suckling'), ('mating', 'mating'), ('lactating', 'lactating'), ('dead', 'dead'), ('unknown', 'unknown')], default='idle', max_length=50)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('dod', models.DateField(blank=True, null=True, verbose_name='date of death')),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('corpse', models.CharField(choices=[('丢弃', '丢弃'), ('实验', '实验'), ('送出', '送出')], default='丢弃', max_length=50)),
                ('born', models.ManyToManyField(blank=True, related_name='litter', to='app.Breed', verbose_name='born breed')),
                ('breed', models.ManyToManyField(blank=True, related_name='parent', to='app.Breed', verbose_name='breed that this mouse engage')),
                ('feed', models.ManyToManyField(blank=True, related_name='mouse', to='app.Feed', verbose_name='feed that this mouse engage')),
                ('genotype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Genotype')),
                ('injectvirus', models.ManyToManyField(blank=True, related_name='mouse', to='app.InjectVirus', verbose_name='virus record for this mouse')),
            ],
        ),
        migrations.CreateModel(
            name='Phenotype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('Black', 'Black'), ('White', 'White'), ('Nake', 'Nake')], default='black', max_length=50)),
                ('note', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Weighting Date')),
                ('weight', models.FloatField(verbose_name='Weight')),
            ],
        ),
        migrations.AddField(
            model_name='mouse',
            name='phenotype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Phenotype'),
        ),
        migrations.AddField(
            model_name='mouse',
            name='weight',
            field=models.ManyToManyField(blank=True, related_name='mouse', to='app.Weight', verbose_name='weight record for this mouse'),
        ),
    ]
