# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mouse',
            name='born',
        ),
        migrations.AddField(
            model_name='mouse',
            name='born',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='litter', to='app.Breed', verbose_name='born breed'),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='genotype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouse', to='app.Genotype', verbose_name='phenotype that this mouse is'),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='phenotype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouse', to='app.Phenotype', verbose_name='phenotype that this mouse is'),
        ),
    ]
