# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161014_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Get_Phenotype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_point', models.DateField(unique=True, verbose_name='check_point')),
                ('date', models.DateField(verbose_name='Weighting Date')),
                ('time', models.TimeField(verbose_name='Weighting Time')),
                ('health', models.CharField(max_length=50, null=True)),
                ('color', models.IntegerField(choices=[(0, 'Black'), (1, 'White'), (2, 'Nake')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Get_Phenotype_Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Weighting Date')),
                ('time', models.TimeField(verbose_name='Weighting Time')),
                ('weight', models.FloatField(verbose_name='Weight')),
                ('to_mouse', models.ManyToManyField(related_name='weight', to='app.Mouse', verbose_name='get weight event to mouse object')),
            ],
        ),
        migrations.CreateModel(
            name='Wean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weam_id', models.CharField(max_length=20)),
                ('weam_start_date', models.DateTimeField(verbose_name='weam Start Date')),
                ('weam_end_date', models.DateTimeField(verbose_name='weam End Date')),
                ('litter', models.IntegerField(default=0)),
                ('to_mouse', models.ManyToManyField(related_name='wean', to='app.Mouse', verbose_name='wean event to mouse object')),
            ],
        ),
        migrations.DeleteModel(
            name='Get_Phenotype_Dynamic',
        ),
        migrations.DeleteModel(
            name='Get_Phenotype_Static',
        ),
        migrations.RemoveField(
            model_name='mate',
            name='litter',
        ),
        migrations.AddField(
            model_name='addbedding',
            name='to_mouse',
            field=models.ManyToManyField(related_name='add_bedding', to='app.Mouse', verbose_name='add bedding event to mouse object'),
        ),
        migrations.AddField(
            model_name='addchow',
            name='to_mouse',
            field=models.ManyToManyField(related_name='add_chow', to='app.Mouse', verbose_name='addchow event to mouse object'),
        ),
        migrations.AddField(
            model_name='adddrink',
            name='to_mouse',
            field=models.ManyToManyField(related_name='add_drink', to='app.Mouse', verbose_name='adddrink event to mouse object'),
        ),
        migrations.AlterField(
            model_name='do_sack',
            name='to_mouse',
            field=models.ManyToManyField(related_name='sack', to='app.Mouse', verbose_name='sack event to mouse object'),
        ),
    ]
