# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161025_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouse',
            name='born_order',
            field=models.IntegerField(null=True),
        ),
    ]
