# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 05:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20161018_0455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Weighting Date')),
                ('time', models.TimeField(verbose_name='Weighting Time')),
                ('weight', models.FloatField(verbose_name='Weight')),
            ],
        ),
        migrations.RemoveField(
            model_name='mouse',
            name='breed',
        ),
        migrations.AddField(
            model_name='mouse',
            name='breed',
            field=models.ManyToManyField(blank=True, null=True, related_name='paternal', to='app.Breed', verbose_name='breed that this mouse engage'),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='phenotype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Phenotype'),
        ),
    ]
