# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_addbedding_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Do_InjectVirus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200, null=True)),
                ('date', models.DateField(verbose_name='Bedding Added Date')),
                ('time', models.TimeField(verbose_name='Bedding Added Time')),
                ('note', models.CharField(max_length=200)),
                ('to_mouse', models.ManyToManyField(related_name='inject_virus', to='app.Mouse', verbose_name='inject virus event to mouse object')),
            ],
        ),
        migrations.RenameModel(
            old_name='AddBedding',
            new_name='Do_AddBedding',
        ),
        migrations.RenameModel(
            old_name='AddChow',
            new_name='Do_AddChow',
        ),
        migrations.RenameModel(
            old_name='AddDrink',
            new_name='Do_AddDrink',
        ),
        migrations.RemoveField(
            model_name='get_genotype',
            name='line',
        ),
        migrations.RemoveField(
            model_name='get_genotype',
            name='locus',
        ),
        migrations.RemoveField(
            model_name='get_genotype',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='get_genotype',
            name='strain',
        ),
        migrations.AddField(
            model_name='get_genotype',
            name='genotype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Genotype'),
        ),
        migrations.AddField(
            model_name='get_genotype',
            name='to_mouse',
            field=models.ManyToManyField(related_name='genotype', to='app.Mouse', verbose_name='get genotype for mouse object'),
        ),
        migrations.AddField(
            model_name='get_phenotype',
            name='to_mouse',
            field=models.ManyToManyField(related_name='phenotype', to='app.Mouse', verbose_name='get phenotype for mouse object'),
        ),
        migrations.AlterField(
            model_name='get_phenotype_weight',
            name='to_mouse',
            field=models.ManyToManyField(related_name='phenotype_weight', to='app.Mouse', verbose_name='get phenotype weight for mouse object'),
        ),
    ]
