# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20161018_0555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='line',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='locus',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='strain',
        ),
        migrations.AddField(
            model_name='feed',
            name='chow',
            field=models.CharField(default='Normal', max_length=200),
        ),
        migrations.AddField(
            model_name='feed',
            name='drink',
            field=models.CharField(default='Normal', max_length=200),
        ),
        migrations.AddField(
            model_name='mouse',
            name='weight',
            field=models.ManyToManyField(blank=True, related_name='mouse', to='app.Weight', verbose_name='weight record for this mouse'),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='breed',
            field=models.ManyToManyField(blank=True, related_name='paternal', to='app.Breed', verbose_name='breed that this mouse engage'),
        ),
        migrations.RemoveField(
            model_name='mouse',
            name='feed',
        ),
        migrations.AddField(
            model_name='mouse',
            name='feed',
            field=models.ManyToManyField(blank=True, related_name='mouse', to='app.Feed', verbose_name='feed that this mouse engage'),
        ),
        migrations.RemoveField(
            model_name='mouse',
            name='injectvirus',
        ),
        migrations.AddField(
            model_name='mouse',
            name='injectvirus',
            field=models.ManyToManyField(blank=True, related_name='mouse', to='app.InjectVirus', verbose_name='virus record for this mouse'),
        ),
    ]
