# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20161025_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouse',
            name='born_order',
            field=models.IntegerField(blank=True, null=True, verbose_name='the order in Breed'),
        ),
    ]
