# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20161018_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='genotyped',
            field=models.BooleanField(default=False),
        ),
    ]
