# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_breed_genotyped'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
