# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20161016_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genotype',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='get_genotype',
            name='mate',
        ),
    ]
