# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20161016_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='get_phenotype',
            name='check_point',
            field=models.DateField(default='VLOJW6CTZQ', unique=True, verbose_name='check_point'),
        ),
    ]
