# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_breed_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Weighting Date')),
                ('health', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='phenotype',
            name='date',
        ),
        migrations.RemoveField(
            model_name='phenotype',
            name='health',
        ),
        migrations.RemoveField(
            model_name='phenotype',
            name='time',
        ),
        migrations.RemoveField(
            model_name='phenotype',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='weight',
            name='time',
        ),
        migrations.AddField(
            model_name='phenotype',
            name='note',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
