# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20161021_0726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breed',
            old_name='litter',
            new_name='litter_count',
        ),
        migrations.AddField(
            model_name='mouse',
            name='born',
            field=models.ManyToManyField(blank=True, related_name='litter', to='app.Breed', verbose_name='breed that this mouse engage'),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='breed',
            field=models.ManyToManyField(blank=True, related_name='parent', to='app.Breed', verbose_name='breed that this mouse engage'),
        ),
    ]
