# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20161021_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='infanticide',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='breed',
            name='pregnant',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='breed',
            name='mate_start_date',
            field=models.DateField(verbose_name='date of mate start'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='born',
            field=models.ManyToManyField(blank=True, related_name='litter', to='app.Breed', verbose_name='born breed'),
        ),
    ]
