# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20161016_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouse',
            name='source',
            field=models.IntegerField(choices=[(0, '饲养产生后代'), (1, '广东省实验动物中心'), (2, '南京模式生物中心'), (9, 'unknown')], default=0),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='status',
            field=models.IntegerField(choices=[(0, 'idle'), (1, 'suckling'), (2, 'mating'), (3, 'lactating'), (4, 'dead'), (9, 'unknown')], default=0),
        ),
    ]
