# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.FileField(upload_to='blog/static/country/flags/'),
        ),
    ]
