# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-11 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20161009_0541'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddBedding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Bedding Added Date')),
                ('time', models.TimeField(verbose_name='Bedding Added Time')),
                ('note', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AddChow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('date', models.DateField(verbose_name='Chow Added Date')),
                ('time', models.TimeField(verbose_name='Chow Added Time')),
                ('amount', models.FloatField(verbose_name='Chow Added Amount')),
            ],
        ),
        migrations.CreateModel(
            name='AddDrink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('date', models.DateField(verbose_name='Drink Added Date')),
                ('time', models.TimeField(verbose_name='Drink Added Time')),
                ('amount', models.FloatField(verbose_name='Drink Amount')),
            ],
        ),
        migrations.CreateModel(
            name='Weighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Weighting Date')),
                ('time', models.TimeField(verbose_name='Weighting Time')),
                ('weight', models.FloatField(verbose_name='Weight')),
            ],
        ),
        migrations.RenameField(
            model_name='mouse',
            old_name='name',
            new_name='mouse_id',
        ),
        migrations.RemoveField(
            model_name='mouse',
            name='role',
        ),
        migrations.RemoveField(
            model_name='mouse',
            name='tmx',
        ),
        migrations.RemoveField(
            model_name='mouse',
            name='training_name',
        ),
        migrations.AddField(
            model_name='genotype',
            name='line',
            field=models.CharField(default='WT', max_length=50),
        ),
        migrations.AddField(
            model_name='mate',
            name='maternal_id',
            field=models.ManyToManyField(related_name='maternal', to='blog.Mouse', verbose_name='maternal mouse object'),
        ),
        migrations.AddField(
            model_name='mate',
            name='paternal_id',
            field=models.ManyToManyField(related_name='paternal', to='blog.Mouse', verbose_name='paternal mouse object'),
        ),
        migrations.AddField(
            model_name='mouse',
            name='dod',
            field=models.DateField(blank=True, null=True, verbose_name='date of death'),
        ),
        migrations.AddField(
            model_name='mouse',
            name='status',
            field=models.IntegerField(choices=[(0, 'weaning'), (1, 'mating'), (2, 'nuring')], default=0),
        ),
        migrations.AlterField(
            model_name='genotype',
            name='name',
            field=models.CharField(default='C57BL/6', max_length=50),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
