# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20161011_0640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='NAME')),
            ],
        ),
        migrations.AlterModelOptions(
            name='person',
            options={},
        ),
        migrations.RemoveField(
            model_name='person',
            name='country',
        ),
        migrations.RemoveField(
            model_name='person',
            name='friendly',
        ),
        migrations.AddField(
            model_name='person',
            name='married',
            field=models.BooleanField(default=False, verbose_name='married'),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='sex',
            field=models.IntegerField(choices=[(0, 'M'), (1, 'F'), (2, '?')], default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=100, verbose_name='full name'),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.AddField(
            model_name='person',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Organization'),
        ),
    ]
