# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20161013_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genotype',
            old_name='name',
            new_name='strain',
        ),
        migrations.RemoveField(
            model_name='mouse',
            name='headplate_color',
        ),
        migrations.AddField(
            model_name='mate',
            name='litter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mouse',
            name='health',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mouse',
            name='name',
            field=models.CharField(default='?', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='sex',
            field=models.IntegerField(choices=[(0, 'M'), (1, 'F'), (2, '?')], default=2),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='status',
            field=models.IntegerField(choices=[(0, 'idle'), (1, 'nuring'), (2, 'mating'), (3, 'weaning')], default=0),
        ),
    ]
