# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20161014_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mouse',
            name='sex',
        ),
        migrations.AddField(
            model_name='genotype',
            name='locus',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='genotype',
            name='sex',
            field=models.IntegerField(choices=[(0, 'M'), (1, 'F'), (2, '?')], default=2),
        ),
        migrations.AddField(
            model_name='mouse',
            name='source',
            field=models.IntegerField(choices=[(0, '饲养产生后代'), (1, '广东省实验动物中心'), (2, '南京模式生物中心')], default=0),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='status',
            field=models.IntegerField(choices=[(0, 'idle'), (1, 'nuring'), (2, 'mating'), (3, 'weaning'), (4, 'sacked'), (5, 'dead')], default=0),
        ),
    ]
